repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    # -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    # -   id: check-json

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.248'
    hooks:
        - id: ruff

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
